# Generated by Django 4.2.13 on 2024-07-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_transaccion_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='valor',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
